const LINE_URL='http://utage-system.com/line/open/nj3MC6diybeh?mtid=PQpm6dNWpMpn';
// TODO: 公開前にLINE以外の各URLを設定。ここだけ変更すれば全リンクに反映されます。
const SITE_LINKS={line:LINE_URL,instagram:'#',about:'#',privacy:'#'};
document.querySelectorAll('[data-link]').forEach(link=>{link.href=SITE_LINKS[link.dataset.link]||'#'});
async function copyText(text){if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return}const area=document.createElement('textarea');area.value=text;area.readOnly=true;area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw new Error('copy failed')}
document.querySelectorAll('[data-copy-target]').forEach(button=>{button.addEventListener('click',async()=>{const target=document.getElementById(button.dataset.copyTarget);try{await copyText(target.innerText);button.textContent='コピーしました ✓';button.classList.add('copied');button.setAttribute('aria-live','polite');setTimeout(()=>{button.textContent='コピーする';button.classList.remove('copied')},2000)}catch{button.textContent='コピーできませんでした';setTimeout(()=>button.textContent='コピーする',2000)}})});
const carousel=document.getElementById('book-carousel');const slides=[...carousel.querySelectorAll('.book-slide')];const counter=document.getElementById('carousel-count');const dots=document.getElementById('carousel-dots');let currentSlide=0;
slides.forEach((_,index)=>{const dot=document.createElement('button');dot.type='button';dot.setAttribute('aria-label',`${index+1}ページ目へ`);dot.addEventListener('click',()=>goToSlide(index));dots.appendChild(dot)});
function goToSlide(index){currentSlide=Math.max(0,Math.min(slides.length-1,index));slides[currentSlide].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});updateCarousel()}
function updateCarousel(){counter.textContent=`${currentSlide+1} / ${slides.length}`;[...dots.children].forEach((dot,index)=>{dot.classList.toggle('active',index===currentSlide);dot.setAttribute('aria-current',index===currentSlide?'true':'false')})}
let scrollTimer;carousel.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{const center=carousel.scrollLeft+carousel.clientWidth/2;currentSlide=slides.reduce((best,slide,index)=>{const a=slide.offsetLeft+slide.offsetWidth/2;const b=slides[best].offsetLeft+slides[best].offsetWidth/2;return Math.abs(a-center)<Math.abs(b-center)?index:best},0);updateCarousel()},80)},{passive:true});
document.querySelector('.prev').addEventListener('click',()=>goToSlide(currentSlide-1));document.querySelector('.next').addEventListener('click',()=>goToSlide(currentSlide+1));carousel.addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();goToSlide(currentSlide+1)}if(event.key==='ArrowLeft'){event.preventDefault();goToSlide(currentSlide-1)}});updateCarousel();
const modal=document.getElementById('image-modal');const modalImage=modal.querySelector('img');const modalCaption=modal.querySelector('p');let modalTrigger=null;
document.querySelectorAll('.zoom-btn').forEach(button=>{button.addEventListener('click',()=>{const image=button.querySelector('img');modalTrigger=button;modalImage.src=image.src;modalImage.alt=image.alt;modalCaption.textContent=button.parentElement.querySelector('figcaption').textContent;modal.showModal()})});
function closeModal(){modal.close();modalImage.src='';modalTrigger?.focus()}modal.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',event=>{if(event.target===modal)closeModal()});modal.addEventListener('cancel',event=>{event.preventDefault();closeModal()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal.open){event.preventDefault();closeModal()}});
